Anykernel3: Adapt for immensity kernel
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>
Change-Id: I450949dd4f42ec4fa5206061f83075495897bf60

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -3,11 +3,11 @@
 # osm0sis @ xda-developers
 
 OUTFD=/proc/self/fd/$2;
-ZIPFILE="$3";
+export ZIPFILE="$3";
 
 BOOTMODE=false;
-ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true;
+ps | grep zygote | grep -v grep >/dev/null && export BOOTMODE=true;
+$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && export BOOTMODE=true;
 
 DIR=/sdcard;
 $BOOTMODE || DIR=$(dirname "$ZIPFILE");
@@ -16,10 +16,16 @@ $BOOTMODE || DIR=$(dirname "$ZIPFILE");
 [ "$AKHOME" ] || AKHOME=$POSTINSTALL/tmp/anykernel;
 [ "$ANDROID_ROOT" ] || ANDROID_ROOT=/system;
 
+$BOOTMODE && AKHOME=/data/local$AKHOME;
+
 ui_print() {
   until [ ! "$1" ]; do
-    echo "ui_print $1
-      ui_print" >> $OUTFD;
+    if $BOOTMODE; then
+      echo "$1";
+    else
+      echo "ui_print $1
+        ui_print" >> $OUTFD;
+    fi;
     shift;
   done;
 }
@@ -28,7 +34,7 @@ ui_printfile() {
     ui_print "$line";
   done < $1;
 }
-show_progress() { echo "progress $1 $2" >> $OUTFD; }
+show_progress() { $BOOTMODE || echo "progress $1 $2" >> $OUTFD; }
 file_getprop() { $BB grep "^$2=" "$1" | $BB cut -d= -f2-; }
 find_slot() {
   local slot=$(getprop ro.boot.slot_suffix 2>/dev/null);
@@ -244,7 +250,7 @@ restore_env() {
 debugging() {
   case $(basename "$ZIPFILE" .zip) in
     *-debugging)
-      ui_print " " "Creating debugging archive in $DIR...";
+      ui_print "  • Creating debugging archive.";
       [ -f /tmp/recovery.log ] && local log=/tmp/recovery.log;
       $BB tar -czf "$DIR/anykernel3-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" $AKHOME $log;
     ;;
@@ -255,7 +261,7 @@ cleanup() {
   rm -rf $AKHOME;
 }
 abort() {
-  ui_print "$@";
+  ui_print " " "!! $*; Aborting!" " ";
   debugging;
   restore_env;
   if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
@@ -266,7 +272,7 @@ abort() {
 do_devicecheck() {
   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
   local device devicename match product testname vendordevice vendorproduct;
-  ui_print "Checking device...";
+  ui_print "  • Checking device.";
   device=$(getprop ro.product.device 2>/dev/null);
   product=$(getprop ro.build.product 2>/dev/null);
   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
@@ -274,14 +280,13 @@ do_devicecheck() {
   for testname in $(file_getprop anykernel.sh 'device.name.*'); do
     for devicename in $device $product $vendordevice $vendorproduct; do
       if [ "$devicename" == "$testname" ]; then
-        ui_print "$testname" " ";
         match=1;
         break 2;
       fi;
     done;
   done;
   if [ ! "$match" ]; then
-    abort " " "Unsupported device. Aborting...";
+    abort "  • Unsupported device. Aborting!";
   fi;
 }
 int2ver() {
@@ -296,7 +301,7 @@ int2ver() {
 do_versioncheck() {
   [ "$(file_getprop anykernel.sh supported.versions)" ] || return 1;
   local android_ver hi_ver lo_ver parsed_ver supported supported_ver;
-  ui_print "Checking Android version...";
+  ui_print "  • Checking Android version.";
   supported_ver=$(file_getprop anykernel.sh supported.versions | $BB tr -d '[:space:]');
   android_ver=$(file_getprop /system/build.prop ro.build.version.release);
   parsed_ver=$(int2ver $android_ver);
@@ -314,16 +319,14 @@ do_versioncheck() {
       fi;
     done;
   fi;
-  if [ "$supported" ]; then
-    ui_print "$android_ver" " ";
-  else
-    abort " " "Unsupported Android version. Aborting...";
+  if [ ! "$supported" ]; then
+    abort "  • Unsupported Android version. Aborting!";
   fi;
 }
 do_levelcheck() {
   [ "$(file_getprop anykernel.sh supported.patchlevels)" ] || return 1;
   local android_lvl hi_lvl lo_lvl parsed_lvl supported_lvl;
-  ui_print "Checking Android security patch level...";
+  ui_print "  • Checking Android security patch level.";
   supported_lvl=$(file_getprop anykernel.sh supported.patchlevels | $BB grep -oE '[0-9]{4}-[0-9]{2}|-');
   android_lvl=$(file_getprop /system/build.prop ro.build.version.security_patch);
   parsed_lvl=$(echo $android_lvl | $BB grep -oE '[0-9]{4}-[0-9]{2}');
@@ -340,7 +343,7 @@ do_levelcheck() {
   if echo -e "$hi_lvl\n$lo_lvl\n$parsed_lvl" | $BB sort -g | $BB grep -n "$parsed_lvl" | $BB grep -q '^2:'; then
     ui_print "$android_lvl" " ";
   else
-    abort " " "Unsupported Android security patch level. Aborting...";
+    abort "  • Unsupported Android security patch level. Aborting!";
   fi;
 }
 dump_moduleinfo() {
@@ -366,7 +369,7 @@ do_modules() {
   local block modcon moddir modtarget module slot umask;
   if [ "$(file_getprop anykernel.sh do.systemless)" == 1 ]; then
     cd $AKHOME/modules;
-    ui_print " " "Creating kernel helper Magisk module...";
+    ui_print "  • Creating kernel helper Magisk module.";
     if [ -d /data/adb/magisk -a -f $AKHOME/split_img/.magisk ]; then
       umask=$(umask);
       umask 022;
@@ -381,11 +384,11 @@ do_modules() {
       cp -f $AKHOME/vertmp $moddir/version;
       umask $umask;
     else
-      ui_print "Magisk installation not found. Skipped!";
+      ui_print "  • Magisk installation not found. Skipped!";
     fi;
   else
     cd $AKHOME/modules;
-    ui_print " " "Pushing modules...";
+    ui_print "  • Pushing modules.";
     if [ -d /dev/block/mapper ]; then
       for block in system vendor product; do
         for slot in "" _a _b; do
@@ -430,14 +433,13 @@ do_modules() {
   cd $AKHOME;
 }
 
-show_progress 1.34 4;
-ui_print " ";
+show_progress 1.34 5;
 cleanup;
 mkdir -p $AKHOME/bin;
 cd $AKHOME;
 unzip -o "$ZIPFILE";
 if [ $? != 0 -o ! "$(ls tools)" ]; then
-  abort "Unzip failed. Aborting...";
+  abort "  • Unzip failed!";
 fi;
 for ARCH32 in x86 arm; do
   if [ -d $AKHOME/tools/$ARCH32 ]; then
@@ -455,22 +457,18 @@ chmod 755 $BB;
 $BB chmod -R 755 tools bin;
 $BB --install -s bin;
 if [ $? != 0 -o -z "$(ls bin)" ]; then
-  abort "Busybox setup failed. Aborting...";
+  abort "  • Busybox setup failed. Aborting!";
 fi;
 
 if [ -f banner ]; then
   ui_printfile banner;
-  ui_print " " " ";
 fi;
 
 KERNEL_STRING="$(file_getprop anykernel.sh kernel.string)";
 ui_print "$KERNEL_STRING";
 if [ -f version ]; then
-  ui_print " ";
   ui_printfile version;
-  ui_print " ";
 fi;
-ui_print " " "AnyKernel3 by osm0sis @ xda-developers" " " " ";
 
 setup_env;
 
@@ -478,12 +476,12 @@ do_devicecheck;
 do_versioncheck;
 do_levelcheck;
 
-ui_print "Installing...";
+ui_print "  • Installing kernel.";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
 [ -f tools/$CORE ] || $BB ln -s $AKHOME/tools/ak*-core.sh $AKHOME/tools/$CORE;
 PATH="$AKHOME/bin:$PATH" home=$AKHOME $BB ash anykernel.sh $2;
 if [ $? != 0 ]; then
-  abort;
+  abort "  • Failed to execute installer.";
 fi;
 
 do_modules;
@@ -495,4 +493,4 @@ if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-ui_print " " " " "Done!";
+ui_print "  • Done!";
